### ISSUE TITLE
I cant even see addon int interface

### ISSUE THREAD

**Issue by Konsolka** [gyakovlev/xCT#7]
I cant see addont in my ESC->INTERFACE. I just downloaded addon

**Comment by gyakovlev** [comment]
wrong repo.
It's repo for original xCT. 
you seem to be running xCT+, chich is a fork that started long ago and now is a completely different addon.

check here.
https://github.com/dandruff/xCT

**Comment by Konsolka** [comment]
Yep i correct my mistake. But it dosent fix my problem that i couldnt see addon in Interface menu

**Comment by gyakovlev** [comment]
@Konsolka I played some wow as legion came out and started the gui config, don't play anymore so it's not being developed and gui config never was finished, just started.
The last working version 1.9d can be found here
https://wow.curseforge.com/projects/xct/files
I don't know if it works now, it used to kinda work as legion came out. 
but better just use xCT+.
