### ISSUE TITLE
I cant see addont in my ESC->INTERFACE. I just downloaded addon

### ISSUE THREAD

**Issue by Konsolka** [gyakovlev/xCT#8]
I had just downloaded addon and couldnt see it in INTERFACE menu. What could I do to fix it?
This is not related to the addon xCT+ because I just deleted it

**Comment by gyakovlev** [comment]
@Konsolka As I answered in other closed issue.
It's not supposed to work as I never finished it.
I played some wow as legion came out and started the gui config, don't play anymore so it's not being developed and gui config never was finished, just started.


The last working version 1.9d can be found here
https://wow.curseforge.com/projects/xct/files
I don't know if it works now, it used to kinda work as legion came out. 
but better just use xCT+.
